version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      kmp-dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "multiplatform-settings"
          - "multiplatform-swiftPackage"
